### ISSUE TITLE
PiZero NVRAM: missing upstream

### ISSUE THREAD

**Issue by macmpi** [Noltari/cypress-nvram#1]
brcmfmac43430-sdio.raspberrypi,model-zero-w.txt file appears to be [missing upstream](https://git.kernel.org/pub/scm/linux/kernel/git/firmware/linux-firmware.git/tree/brcm).
This impacts many distributions.

**Comment by Noltari** [comment]
> brcmfmac43430-sdio.raspberrypi,model-zero-w.txt file appears to be [missing upstream](https://git.kernel.org/pub/scm/linux/kernel/git/firmware/linux-firmware.git/tree/brcm).
> This impacts many distributions.

@macmpi This should be reported (upstream) to the Raspberry Pi foundation.
OpenWrt is a downstream distribution depending on RPi Foundation's published source code and firmwares.
