### ISSUE TITLE
brcmfmac43455-sdio.raspberrypi,4-compute-module.txt missing?

### ISSUE THREAD

**Issue by march1993** [Noltari/cypress-nvram#2]
It seems a direct copy of `brcmfmac43455-sdio.raspberrypi,4-model-b.txt` would work.

**Comment by BKPepe** [comment]
Fixed in [OpenWrt base repository](https://github.com/openwrt/openwrt/commit/b1db5585557ed069027767a80c31c6f1f2920196) for master branch.

**Comment by march1993** [comment]
nice to here that
